news_曝《龙腾4》跨性别总监离职！工作室恐被关闭.html:
  link: http://news.17173.com/content/01172025/182103536.shtml
  md5: fdf6ff507fec530c9f69e227f507451f
  title: 曝《龙腾4》跨性别总监离职！工作室恐被关闭
  snippet: 据外媒爆料，《龙腾世纪4》的跨性别总监Corinne Busche现已从Bioware和EA离职。 此外，爆料还称负责开发《龙腾世纪4》的BioWare埃德蒙顿工作室将于2025年2月关闭。
  visited_date: '2025-01-21 03:24:13'
chinese_特朗普会阻止“跨性别疯狂”吗？.html:
  link: https://chinese.aljazeera.net/news/political/2024/12/25/%E7%89%B9%E6%9C%97%E6%99%AE%E4%BC%9A%E9%98%BB%E6%AD%A2%E8%B7%A8%E6%80%A7%E5%88%AB%E7%96%AF%E7%8B%82%E5%90%97
  md5: 11526927a94e0b267766ad3b708c09c6
  title: 特朗普会阻止“跨性别疯狂”吗？
  snippet: 复杂性和阻碍性. 与禁止男女性别歧视相反，跨性别身份并未得到宪法承认，这将使跨性别者在基于性别的歧视方面的法律地位变得复杂化和受到阻碍。 共和党保守派获得6
    票多数，而...
  visited_date: '2025-01-21 03:35:18'
guangming_切肋骨瘦腰还想制成皇冠美国变性网红疯狂举动惹议_国际__2025-01-21.html:
  link: https://guangming.com.my/%E5%88%87%E8%82%8B%E9%AA%A8%E7%98%A6%E8%85%B0%E8%BF%98%E6%83%B3%E5%88%B6%E6%88%90%E7%9A%87%E5%86%A0-%E7%BE%8E%E5%9B%BD%E5%8F%98%E6%80%A7%E7%BD%91%E7%BA%A2%E7%96%AF%E7%8B%82%E4%B8%BE%E5%8A%A8%E6%83%B9
  md5: a0668b077b8adcab49104441bf568041
  title: 切肋骨瘦腰还想制成皇冠美国变性网红疯狂举动惹议| 国际 | 2025-01-21
  snippet: （华盛顿21日讯）美国堪萨斯城的一个变性女网红，进行了切除部分肋骨的手术，只为让腰围变细；手术后她更要求收藏被取出的肋骨，可能打算用来制作一顶皇冠，让人听了浑身不...
  visited_date: '2025-01-21 03:35:48'
guangming_英钩协官宣禁跨性别参加女钩赛_精选_体育__2025-01-09.html:
  link: https://guangming.com.my/%E8%8B%B1%E9%92%A9%E5%8D%8F%E5%AE%98%E5%AE%A3-%E7%A6%81%E8%B7%A8%E6%80%A7%E5%88%AB%E5%8F%82%E5%8A%A0%E5%A5%B3%E9%92%A9%E8%B5%9B
  md5: 16552e80c93cd4a26cbe0268e31e08b6
  title: 英钩协官宣禁跨性别参加女钩赛| 精选| 体育 | 2025-01-09
  snippet: （伦敦9日讯）英格兰钩球协会宣布，从下赛季开始，禁止跨性别女性参加女子组别的比赛。 为解决跨性别和非二元性别者的参与问题，英格兰钩球协会设立了两个比赛类别：女子组和...
  visited_date: '2025-01-21 03:36:07'
i_有点像打雷姐（跨性别版）.html:
  link: https://i.ifeng.com/c/8g5XQOZgslj
  md5: c388b91513e7793277e63a2014fae1ad
  title: 有点像打雷姐（跨性别版）
  snippet: 全球首位跨性别戛纳影后Karla Sofía Gascón 最近在美国颁奖季度横扫。 “特别声明：以上作品内容(包括在内的视频、图片或音频)为凤凰网旗下自媒体平台“大风号”用户上传并...
  visited_date: '2025-01-21 03:36:43'
news_《龙腾4》跨性别总监离职_玩家快失业别祸害别的游.html:
  link: https://news.17173.com/content/01182025/170301755.shtml
  md5: 2b35d95a87834a787d015fcafdd1cf10
  title: 《龙腾4》跨性别总监离职 玩家:快失业别祸害别的游
  snippet: 昨日据外媒爆料，《龙腾世纪：影障守护者》的跨性别总监Corinne Busche现已从Bioware和EA离职，业内知名人士Jeff Grubb也证实了这一点。曝出的告别邮件中，Corinne
    Busche...
  visited_date: '2025-01-21 03:42:54'
news_美国通过立法：禁止跨性别女学生参加中小学校的女生体育项目.html:
  link: https://news.mydrivers.com/1/1025/1025568.htm
  md5: 3221923936f957176dbcf17e85d018ea
  title: 美国通过立法：禁止跨性别女学生参加中小学校的女生体育项目
  snippet: 1月16日消息，据国外媒体报道称，美国众议院今天通过立法，禁止跨性别女学生参加中小学校的女生体育项目。这项法案以218票对206票，几乎完全按照党派划线获得通过，...
  visited_date: '2025-01-21 03:43:26'
news_英国跨性别模特“隐瞒实情”和男孩亲密，遭当街报复，19岁孤女是领头者.html:
  link: https://news.qq.com/rain/a/20250117A00YJH00
  md5: e6c20f342d529ea4be74e36885f99ff6
  title: 英国跨性别模特“隐瞒实情”和男孩亲密，遭当街报复，19岁孤女是领头者
  snippet: 当地时间1月16日，伦敦警察厅公布了一段由街头监控拍下的视频，可以看到戴着面具和手套的蒙面歹徒埋伏在停车场等待，当面带微笑的毫无戒心的受害者靠近时，他们对她拳打脚...
  visited_date: '2025-01-21 03:44:00'
std_专栏乔靖夫│跨性别选手遭杯葛风暴_星岛日报.html:
  link: https://std.stheadline.com/sc/realtime/article/2044914/%E5%8D%B3%E6%99%82-%E9%AB%94%E8%82%B2-%E5%B0%88%E6%AC%84-%E5%96%AC%E9%9D%96%E5%A4%AB%E2%94%82%E8%B7%A8%E6%80%A7%E5%88%A5%E9%81%B8%E6%89%8B%E9%81%AD%E6%9D%AF%E8%91%9B%E9%A2%A8%E6%9A%B4
  md5: f1d217ffa3b1e3892c92f3c48aa2b500
  title: 专栏乔靖夫│跨性别选手遭杯葛风暴| 星岛日报
  snippet: 早前的巴黎奥运因为女性拳击选手的性别被质疑而引起颇大风波，其实关于跨性别运动员的争议在西方国家体育界一直在燃烧，近期比较瞩目的是美国西.
  visited_date: '2025-01-21 03:44:42'
stnn_特朗普：美官方政策仅2种性别，不让“男性”参加女子赛事.html:
  link: https://stnn.cc/c/2024-12-23/3944707.shtml
  md5: 69756e994e3a85edecc2778f0491ca43
  title: 特朗普：美官方政策仅2种性别，不让“男性”参加女子赛事
  snippet: 美国总统当选人特朗普周日前往亚利桑那州凤凰城参加保守派年度盛会“AmericaFest大会”，期间提到跨性别议题，强调要结束“跨性别的疯狂举动”，要将跨性别者逐出军队和小学、...
  visited_date: '2025-01-21 03:45:12'
stnn_联邦法庭裁定违宪，拜登政府跨性别学生保护举措受挫.html:
  link: https://stnn.cc/c/2025-01-10/3949453.shtml
  md5: 659f3b26a1f4aab3c8b63b4b1e7d3e2a
  title: 联邦法庭裁定违宪，拜登政府跨性别学生保护举措受挫
  snippet: 肯塔基州联邦法庭裁定，拜登政府无权扩大为了保障跨性别学生，而扩大《教育法修正案第九条》（Title IX）的适用范围，教育部的行为超越职权，也侵犯了教师的言论自由。
  visited_date: '2025-01-21 03:45:45'
www_曝《龙腾4》跨性别总监离职！工作室恐被关闭.html:
  link: https://www.163.com/dy/article/JM3O1NR40526K1KN.html
  md5: 19ffb40026ae658804e6381e2e139f22
  title: 曝《龙腾4》跨性别总监离职！工作室恐被关闭
  snippet: 据外媒爆料，《龙腾世纪4》的跨性别总监CorinneBusche现已从Bioware和EA离职。此外，爆料还称负责开发《龙腾世纪4》的BioWare埃德蒙顿工作室将于2025年2月关闭。
  visited_date: '2025-01-21 03:56:56'
www_1152025_川普国防部长确认听证会；民主党抹黑新投票通过的禁跨性别学生参加女子运动法案.html:
  link: https://www.bannedbook.org/bnews/sohnews/20250116/2142162.html
  md5: 0cfb865f09903cb6db66794078e8256c
  title: 1/15/2025 川普国防部长确认听证会；民主党抹黑新投票通过的禁跨性别学生参加女子运动法案
  snippet: '来源: US News Express美国时事通, 文章内容并不代表本网立场和观点。 1/15/2025 川普国防部长确认听证会；民主党抹黑新.
    感恩您的捐赠、点赞、留言和和关注！'
  visited_date: '2025-01-21 04:02:45'
www_美国众议院通过法案_限制跨性别学生参与体育竞赛.html:
  link: https://www.bannedbook.org/bnews/sports/20250116/2141902.html
  md5: 1cbef296d42c0894f4679e9402e65554
  title: 美国众议院通过法案 限制跨性别学生参与体育竞赛
  snippet: 美国联邦众议院今天通过共和党籍候任总统川普支持的一项法案，对没有遵守规定的学校扣留联邦资金，实质上禁止跨性别女孩与妇女参与学校体育竞赛。 美国联邦众议院通过...
  visited_date: '2025-01-21 04:03:09'
www_台湾跨性别老师黄明真：从被逼离职到获“教育界奥斯卡奖”师铎奖，社会真的更包容多元了吗？.html:
  link: https://www.bbc.com/zhongwen/articles/crmnp990px7o/simp
  md5: 3441e5abdd38babdf8c1ca0b89459f2e
  title: 台湾跨性别老师黄明真：从被逼离职到获“教育界奥斯卡奖”师铎奖，社会真的更包容多元了吗？
  snippet: 台湾教师黄明真获颁教育部最高荣誉奖，她相隔近20年两度上新闻，台湾社会风气有所改变。但她仍认为“我不是第一”。
  visited_date: '2025-01-21 04:03:40'
www_跨性别：中国高校公示学生出柜信息引争议.html:
  link: https://www.bbc.com/zhongwen/articles/czxkv0qzqwzo/simp
  md5: 857737d0a971279303cba093a08a827f
  title: 跨性别：中国高校公示学生出柜信息引争议
  snippet: 华中科技大学将一位跨性别女性在校生变更身份证性别的详情资料张贴公示，文件详细记录学生姓名以及资讯更新缘由。此举引发民众关于个人隐私过度揭露的惶恐。
  visited_date: '2025-01-21 04:04:05'
www_跨性别女切6根肋骨瘦身_还打算制肋骨皇冠.html:
  link: https://www.chinapress.com.my/20250115/%E8%B7%A8%E6%80%A7%E5%88%AB%E5%A5%B3%E5%88%876%E6%A0%B9%E8%82%8B%E9%AA%A8%E7%98%A6%E8%BA%AB-%E8%BF%98%E6%89%93%E7%AE%97%E5%88%B6%E8%82%8B%E9%AA%A8%E7%9A%87%E5%86%A0/
  md5: 0e618104d800ad058a48e663db4c0dac
  title: 跨性别女切6根肋骨瘦身 还打算制肋骨皇冠
  snippet: （华盛顿15日综合电）美国一名跨性别女子为了追求纤细的腰身，不惜动手术取出六根肋骨。更令人惊讶的是，为了不要“浪费”，她打算用这些取出的肋骨，做成一顶“肋骨皇冠”，...
  visited_date: '2025-01-21 04:04:33'
www_特朗普重入白宫｜特朗普终止多元性别_美国只承认男和女.html:
  link: https://www.chinapress.com.my/20250121/%E7%89%B9%E6%9C%97%E6%99%AE%E9%87%8D%E5%85%A5%E7%99%BD%E5%AE%AB%EF%BD%9C%E7%89%B9%E6%9C%97%E6%99%AE%E7%BB%88%E6%AD%A2%E5%A4%9A%E5%85%83%E6%80%A7%E5%88%AB-%E7%BE%8E%E5%9B%BD%E5%8F%AA%E6%89%BF%E8%AE%A4/
  md5: 7790d75e211079fd439ef27daaf436d2
  title: 特朗普重入白宫｜特朗普终止多元性别 美国只承认男和女
  snippet: （华盛顿21日综合电）美国总统特朗普20发表就职演说，誓言将法律秩序带回社会，他宣布终止多元性别，并表示从今天起，美国政府的正式政策将只有两种性别：男性和女性。
  visited_date: '2025-01-21 04:05:02'
www_未成年变性手术卫福部称仅限双性人-_生活新闻-_中国时报.html:
  link: https://www.chinatimes.com/cn/newspapers/20250114000453-260114?ctrack=mo_main_recmd_p15
  md5: ba9c755beee1be37a4c21e071916a3ac
  title: 未成年变性手术卫福部称仅限双性人- 生活新闻- 中国时报
  snippet: 卫福部去年底订定「LGBT+民眾医疗照护参考指引」，其中「未成年双性人之医疗手术共同性建议原则」提出，对于12到18岁有适应困难者，经专业团队评估后可进行手术，...
  visited_date: '2025-01-21 04:05:20'
www_未成年可做變性手術惹議_家長團體憂心國外後悔案例多.html:
  link: https://www.epochtimes.com/gb/25/1/14/n14413337.htm
  md5: b5d4ca5d680ed86151b16b3548c3c737
  title: 未成年可做變性手術惹議 家長團體憂心國外後悔案例多
  snippet: 卫福部去年底公告“LGBT+民众医疗照护参考指引”，开放未成年的12到18岁儿少，有条件准许、执行变性手术，家长团体14日表示，青春期的青少年身心灵发育都还在迈向成熟的阶段，...
  visited_date: '2025-01-21 04:16:44'
www_活跃在中国和世界舞台的朝鲜族变性舞蹈演员金星(57岁)的演出在中国国内接连被取消，其背景备受关注。.html:
  link: https://www.mk.co.kr/cn/world/11209966
  md5: f369ccbc95333bb9e5f19728f70044f6
  title: 活跃在中国和世界舞台的朝鲜族变性舞蹈演员金星(57岁)的演出在中国国内接连被取消，其背景备受关注。
  snippet: 3日(当地时间)，据CNN等媒体报道，最近中国当局无缘无故突然取消著名变性人金兴的演出的事例正在增加。 去年年末,广州以"文件不足"为由取消了晋兴的剧场演出,其他地区的...
  visited_date: '2025-01-21 04:39:00'
www_曝《龙腾4》跨性别总监离职！_工作室恐被关闭.html:
  link: https://www.msn.com/zh-cn/gaming/other/%E6%9B%9D-%E9%BE%99%E8%85%BE4-%E8%B7%A8%E6%80%A7%E5%88%AB%E6%80%BB%E7%9B%91%E7%A6%BB%E8%81%8C-%E5%B7%A5%E4%BD%9C%E5%AE%A4%E6%81%90%E8%A2%AB%E5%85%B3%E9%97%AD/ar-AA1xlp3k
  md5: 804eae4c1e99777483b7579abac9dc4f
  title: 曝《龙腾4》跨性别总监离职！ 工作室恐被关闭
  snippet: 据外媒爆料，《龙腾世纪4》的跨性别总监Corinne Busche现已从Bioware和EA离职。
  visited_date: '2025-01-21 04:39:38'
www_變性者參與女子體育賽事？_加州議員提案禁止.html:
  link: https://www.ntdtv.com/gb/2025/01/16/a103948580.html
  md5: 4b032c0d7ce25f0662fbced958b494c7
  title: 變性者參與女子體育賽事？ 加州議員提案禁止
  snippet: 【新唐人北京时间2025年01月16日讯】周二（14日），美国国会众议院通过了“禁止跨性别学生参与女子体育赛事”的法案，同时，加州共和党立法者也提出了一项类似的提案，确保只有...
  visited_date: '2025-01-21 04:45:29'
www_【特朗普重返白宫】特朗普扬言“制止LGBTQ疯狂行为”.html:
  link: https://www.orientaldaily.com.my/news/international/2024/12/23/701286
  md5: db451cab16e03dda2ad96ae02193840f
  title: 【特朗普重返白宫】特朗普扬言“制止LGBTQ疯狂行为”
  snippet: （菲尼克斯23日讯）美国候任总统特朗普当地时间周日誓言，在他上任的第一天就“制止跨性别者的疯狂行为”，而即将控制美国国会两院和白宫的共和党，将继续反对LGBTQ（同性恋、...
  visited_date: '2025-01-21 04:45:49'
www_【特朗普重返白宫】特朗普2.0终止多元性别_只承认男性和女性.html:
  link: https://www.orientaldaily.com.my/news/international/2025/01/21/707331
  md5: 0d0f309f96ba152ae22fe7bd0ebba50c
  title: 【特朗普重返白宫】特朗普2.0终止多元性别 只承认男性和女性
  snippet: （华盛顿21日讯）重返白宫的特朗普当地时间周一发表就职演说，誓言将法律秩序带回社会，他宣布终止多元性别，并表示从今天起，他领导下美国政府的正式政策将只有两种性别：...
  visited_date: '2025-01-21 04:46:12'
www_健身房更衣室遇跨性別者_華女感不適.html:
  link: https://www.worldjournal.com/wj/story/121359/8473298?zh-cn
  md5: 7ec8b3804d07bf96b1d3027d084107fd
  title: 健身房更衣室遇跨性別者 華女感不適
  snippet: 南加州天普市（Temple City）一家连锁健身房女性更衣室，华人陈小姐发现一名外表疑似男性的用户。当她向工作人员报...
  visited_date: '2025-01-21 05:18:47'
www_又抹黑跨性別_川普：美官方政策將只有兩種性別.html:
  link: https://www.worldjournal.com/wj/story/124279/8442721?zh-cn
  md5: 7b34c65ba2f02958952cab6cc6583286
  title: 又抹黑跨性別 川普：美官方政策將只有兩種性別
  snippet: 总统当选人川普今天矢言于上任首日「停止跨性别精神错乱」。他并承诺「不让男性参加女子体育」，并强调美国政府的官方政策「将只...
  visited_date: '2025-01-21 05:30:04'
www_《龙腾4》跨性别总监离职_玩家快失业别祸害别的游.html:
  link: https://www.yeeyi.com/news/details/2591668/
  md5: 7c00a1b8b90dc294f3325f2f46fc3084
  title: 《龙腾4》跨性别总监离职 玩家:快失业别祸害别的游
  snippet: 昨日据外媒爆料，《龙腾世纪：影障守护者》的跨性别总监Corinne Busche现已从Bioware和EA离职，业内知名人士Jeff Grubb也证实了这一点。
  visited_date: '2025-01-21 05:30:28'
www_姚耀光：厕所的争论.html:
  link: https://www.zaobao.com.sg/lifestyle/columns/story20250111-5697106
  md5: 3580e905479e724a0de6b1ed6cde5ae4
  title: 姚耀光：厕所的争论
  snippet: 去年底，美国民主党众议员萨拉·麦克布莱德（Sarah McBride）成为美国首位当选国会议员的跨性别者，这一历史性事件引发了一场关于厕所使用的争论。
  visited_date: '2025-01-21 05:36:31'
