.:
  name: .
  description: 根目录，按照内容与来源分类
凤凰网:
  name: 凤凰网
  description: 该目录收录了许多关于变性人与性别认同相关的报道，内容涵盖个人的生命故事、变性手术的经历、家庭与社会的反应等，旨在呈现跨性别群体在社会中的生存现状与挑战。
新浪新闻:
  name: 新浪新闻
  description: 该目录包含关于跨性别者的新闻报道，涉及跨性别者在不同年龄和性别身份下的经历与挑战，包括性别过渡手术、家庭和社会反应等。报道反映了跨性别人群在法律、医疗以及社会环境中的现状和相关案例。
澎湃新闻:
  name: 澎湃新闻
  description: 该目录收录了与跨性别相关的新闻文章和评论，内容涵盖跨性别者的生活故事、过渡经历、法律政策、社会环境及健康医疗等多个方面，反映了跨性别者在现代社会中面临的挑战和问题。
