.:
  name: .
  description: 根目录，按照内容与来源分类
凤凰网:
  name: 凤凰网
  description: 本目录收录了关于跨性别主题的多样内容，包括文化评论、社会案例以及个体故事等，意在提高对跨性别群体的理解和认知。
新浪新闻:
  name: 新浪新闻
  description: 本目录包含了与跨性别相关的多种讨论和资讯，包括生命故事、社会认同、变装经验、艺术表达等，旨在提供一个全面而真实的跨性别视角。
澎湃新闻:
  name: 澎湃新闻
  description: 澎湃新闻目录收录了多个与跨性别相关的新闻文章，涵盖了医疗和心理健康、法律政策、社会环境等方面的内容，体现了跨性别者在生活中所面临的各种挑战与经历。
