.:
  name: .
  description: 根目录，按照内容与来源分类
凤凰网:
  name: 凤凰网
  description: 此目录包含与跨性别相关的新闻报道，记录了个人生命故事、变性经历及其对家庭与社会的影响。内容既包括不同年龄段的变性案例，也涉及社会对于变性者的反应与同情，展示了跨性别者在生活和文化中的多元表现。
新浪新闻:
  name: 新浪新闻
  description: 此目录包含来自新浪新闻关于跨性别者的相关报道，涉及从变性手术的案例到法律与社会环境的探讨。这些故事展示了跨性别者的经历与挑战，反映了社会对跨性别者的认知与态度变化。
