.:
  name: .
  description: 根目录，按照内容与来源分类
中国新闻网:
  name: 中国新闻网
  description: 中国新闻网，是知名的中文新闻门户网站，也是全球互联网中文新闻资讯最重要的原创内容供应商之一。本目录收录了中国新闻网与跨性别相关的一系列新闻报道和个人故事，涉及跨性别者在军事服役、法律政策、以及自身经历和社会接受度等方面的内容。这些资料展现了跨性别者在社会中的挑战与奋斗，也记录了相关政策的变化和影响。
凤凰网:
  name: 凤凰网
  description: 凤凰网是凤凰新媒体旗下的一个图文音、视频综合资讯网站。提供国际、中国大陆及港、澳、台地区的时政、社会、财经、娱乐、时尚、生活等综合新闻信息。凤凰网收录了一系列跨性别相关的文章和资讯，涵盖了文化、娱乐、时尚、金融及心理等多个领域，探讨了跨性别者的生活经历、社会挑战、以及对性别认同的深入思考。
搜狐新闻:
  name: 搜狐新闻
  description: 这是搜狐新闻中收录的一系列与跨性别相关的文章和报道，内容涵盖了跨性别者的生活故事、社会现状、时尚领域的表现以及医疗经验分享等，旨在为公众提供一个多维度了解跨性别群体的平台。
新浪新闻:
  name: 新浪新闻
  description: 新浪新闻是新浪集团旗下的智能信息平台。此目录包含新浪新闻与跨性别相关的内容，涵盖变装文化、跨性别者自述、法律政策和社会环境影响等多个方面。
未分类:
  name: 未分类
  description: 这个目录收录了未分类的各种网站与跨性别相关的多种内容，涉及了跨性别者的生活故事、经历分享、医疗资源、法律政策、社会环境等多个方面。诸如‘生活所迫我沦为泰国人妖靠药物维持美貌’的个人叙述展示了跨性别者在社会压力与自身认同之间的挣扎；而‘变性手术_-_中国人民公安大学出版社’则提供了关于跨性别手术的重要医疗信息，助力更多人了解和选择合适的医疗服务。此外，部分文件反映了社会对跨性别群体的偏见与挑战，如‘日本军方爆出性丑闻“异装癖”军官换装混入女浴池’的事件引起了公众对跨性别者处境的广泛关注；而‘若林佑马将在他以跨性别者身份执导的电影《52赫兹鲸鱼》的脱口秀’则展示了跨性别者在文化艺术领域的发展与探索。这些资料的重要性不仅在于记录他们的生存状态，也在于为未来的社会变革提供支持与参考。
澎湃新闻:
  name: 澎湃新闻
  description: 澎湃新闻目录中包含了多个与跨性别相关的案例报道及社会问题探讨，涵盖了个人生活故事、变性手术带来的法律与社会挑战、跨性别人士遭遇的歧视等。
网易新闻:
  name: 网易新闻
  description: 该目录包含了网易新闻与跨性别相关的新闻与讨论，涵盖变性手术、公众认同、性别认同教育、文化表达等方方面面的内容。
腾讯新闻:
  name: 腾讯新闻
  description: 本目录收录了腾讯新闻与跨性别相关的新闻报道，涵盖了跨性别人士的生活故事、社会支持、医疗资源、法律政策以及文化表达等多方面内容，为用户提供了多维度的信息视角，帮助了解跨性别群体在社会中的现状与挑战。
