.:
  name: .
  description: 根目录，按照内容与来源分类
中国新闻网:
  name: 中国新闻网
  description: 本目录收录了与跨性别相关的一系列新闻报道和个人故事，涉及跨性别者在军事服役、法律政策、以及自身经历和社会接受度等方面的内容。这些资料展现了跨性别者在社会中的挑战与奋斗，也记录了相关政策的变化和影响。
凤凰网:
  name: 凤凰网
  description: 凤凰网收录了一系列跨性别相关的文章和资讯，涵盖了文化、娱乐、时尚、金融及心理等多个领域，探讨了跨性别者的生活经历、社会挑战、以及对性别认同的深入思考。这些内容反映了跨性别群体的多样性与面临的社会问题，旨在提升公众对跨性别事务的理解与接纳。
搜狐新闻:
  name: 搜狐新闻
  description: 这是搜狐新闻中收录的一系列与跨性别相关的文章和报道，内容涵盖了跨性别者的生活故事、社会现状、时尚领域的表现以及医疗经验分享等，旨在为公众提供一个多维度了解跨性别群体的平台。
新浪新闻:
  name: 新浪新闻
  description: 此目录包含与跨性别相关的内容，涵盖变装文化、跨性别者自述、法律政策和社会环境影响等多个方面。内容包括变装活动、跨性别者的生活体验、以及对跨性别群体的社会态度等深入探讨，旨在为公众提供全面的跨性别信息与知识。
澎湃新闻:
  name: 澎湃新闻
  description: 澎湃新闻目录中包含了多个与跨性别相关的案例报道及社会问题探讨，涵盖了个人生活故事、变性手术带来的法律与社会挑战、跨性别人士遭遇的歧视等。这些内容不仅反映了跨性别群体的生存现状，也为公众提供了有关跨性别者的医疗资源、心理健康、法律政策的深入了解。
