.:
  name: .
  description: 根目录，按照内容与来源分类
凤凰网:
  name: 凤凰网
  description: 凤凰网收录了一系列跨性别相关的文章和资讯，涵盖了文化、娱乐、时尚、金融及心理等多个领域，探讨了跨性别者的生活经历、社会挑战、以及对性别认同的深入思考。这些内容反映了跨性别群体的多样性与面临的社会问题，旨在提升公众对跨性别事务的理解与接纳。
新浪新闻:
  name: 新浪新闻
  description: 此目录包含与跨性别相关的内容，涵盖变装文化、跨性别者自述、法律政策和社会环境影响等多个方面。内容包括变装活动、跨性别者的生活体验、以及对跨性别群体的社会态度等深入探讨，旨在为公众提供全面的跨性别信息与知识。
澎湃新闻:
  name: 澎湃新闻
  description: 澎湃新闻目录中包含了多个与跨性别相关的案例报道及社会问题探讨，涵盖了个人生活故事、变性手术带来的法律与社会挑战、跨性别人士遭遇的歧视等。这些内容不仅反映了跨性别群体的生存现状，也为公众提供了有关跨性别者的医疗资源、心理健康、法律政策的深入了解。
