url_mappings:
  - domain: "sina.com"
    dir: "新浪新闻"
  - domain: "sina.cn"
    dir: "新浪新闻"
  - domain: "news.qq.com"
    dir: "腾讯新闻"
  - domain: "163.com"
    dir: "网易新闻"
  - domain: "thepaper.cn"
    dir: "澎湃新闻"
  - domain: "sohu.com"
    dir: "搜狐新闻"
  - domain: "ifeng.com"
    dir: "凤凰网"
  - domain: "chinanews.com"
    dir: "中国新闻网"
  - domain: "*"
    dir: "未分类"
