00f25ae31b3262d110e5dc74a4843e14:
  link: http://www.msn.com/zh-cn/news/other/%E9%9F%A9%E5%9B%BD%E7%94%B7%E6%98%9F%E6%9C%B4%E6%88%90%E5%8B%8B%E5%9C%A8-%E9%B1%BF%E9%B1%BC%E6%B8%B8%E6%88%8F2-%E6%89%AE%E6%BC%94%E8%B7%A8%E6%80%A7%E5%88%AB%E5%A5%B3%E6%80%A7%E5%BC%95%E4%BA%89%E8%AE%AE/ar-AA1vmNvr?apiversion=v2&noservercache=1&domshim=1&renderwebcomponents=1&wcseo=1&batchservertelemetry=1&noservertelemetry=1
  snippet: 《鱿鱼游戏》第二季将于2024年12月26日在网飞播出。新一季不仅有原班人马，还加入许多新卡司。因《黑暗荣耀》走红的朴成勋也加入，他将饰演一名跨性别女性。
  title: 韩国男星朴成勋在《鱿鱼游戏2》 扮演跨性别女性引争议
  visited_date: '2025-01-12 17:28:29'
02cca1e92f630d4f8ae4c4c4b417ff01:
  link: https://info.51.ca/articles/1370260
  snippet: 川普计划在他任职的第一天签署行政命令，将从美国军队清退所有跨性别军人，预计这将让15000名士兵离开部队，同时该命令还将禁止跨性别新兵加入。
  title: 川普将清退美军跨性别军人，终结奥巴马政治遗产_无忧资讯
  visited_date: '2025-01-12 17:37:57'
05b33e64091bff07b9925b0349b82459:
  link: https://news.qq.com/rain/a/20241129A07Y6X00
  snippet: 2024年11月，历史性的时刻来临，美国迎来了首位跨性别议员——萨拉·麦克布莱德。 她当选为特拉华州众议院的唯一席位，成为美国历史上最具象征意义的跨性别民选官员之一。
  title: 美国首位跨性别国会议员入职，众议长先发制人：你只能用男厕所
  visited_date: '2025-01-12 17:47:50'
092809dcb566056bfe040317d6b8dd13:
  link: https://uschinapress.com/article/191980.html
  snippet: 美国最高法院周三听取了关于田纳西州禁止未成年人接受性别确认治疗的法律挑战，并且可能支持该禁令。这是最高法院第二次审理重大跨性别权利案件。
  title: 最高院可能支持田纳西州禁令 阻止对未成年人进行变性治疗
  visited_date: '2025-01-12 17:52:26'
0ec7263227a3386cb023e334e3507ab1:
  link: https://hk.on.cc/hk/bkn/cnt/news/20241212/bkn-20241212191131535-1212_00822_001_cn.html?view=d
  snippet: 网上近日流传一份盖有湖北省华中科技大学同济医学院护理学院公章的公示，显示一名男学生向护理学院提交个人基本身份资讯变更申请，因进行变性手术，申请其性别资讯由男...
  title: 学生接受变性手术院校公开个人身份资讯惹议｜即时新闻｜中港台｜on.cc东网
  visited_date: '2025-01-12 17:35:38'
1fa881f9105c5b55c0cde8b26532169a:
  link: https://hk.on.cc/hk/bkn/cnt/news/20241220/bkn-20241220190357126-1220_00822_001_cn.html?view=d
  snippet: 内地知名跨性别舞蹈家、节目主持人金星近期在内地多场舞蹈和舞台剧演出被取消，外界怀疑与她年初公开展示象征支持多元性别（LG...
  title: 4地演出被取消跨性别舞蹈家称与地方管理者有误会｜即时新闻｜中港台｜on.cc东网
  visited_date: '2025-01-12 17:36:30'
2330811552010104ad9db82f472eb1a8:
  link: https://www.bannedbook.org/bnews/topimagenews/20241223/2132097.html
  snippet: 美国总统当选人川普今天矢言于上任首日“停止跨性别精神错乱”。他并承诺“不让男性参加女子体育”，并强调美国政府的官方政策“将只有两种性别：男性和女性”。
  title: “停止跨性别精神错乱”！川普：美官方政策将只有两种性别
  visited_date: '2025-01-12 18:00:03'
26b8b2b9062a1fb5305db83c3ba6ca4a:
  link: https://voi.id/zh/lifestyle/440525
  snippet: 雅加达- Netflix 发布了最新视频,其中包含Squid Game 2 系列角色的解释。从几个旧角色到一个新的角色,这个系列将继续Seong
    Gi Hun(Lee Jung Jae)寻找游戏背后的策划者...
  title: 朴成贤成人变成跨性别者,古老新人物名单2
  visited_date: '2025-01-12 17:54:10'
397d4f13632f4f352d28e9f0a4b0dd78:
  link: https://www.163.com/dy/article/JIDT1LPG0526D8LR.html
  snippet: 今年年初迪士尼发布了《小美人鱼》音乐舞台剧选角公告，其中提到女主爱丽儿和男主亚力克必须由跨性别者饰演。近日有网友发现，迪士尼偷偷修改了表述方式。
  title: 迪士尼为《小美人鱼》舞台剧选主角 必须跨性别者演
  visited_date: '2025-01-12 17:56:31'
3d6dc3896f64b2ae1e8fd19b01435c57:
  link: https://news.seehua.com/post/1249909
  snippet: 特朗普计划禁跨性别者服役，美军1.5万现役军人恐受影响！ 据外媒报导，美国前总统特朗普计划在重返白宫后，于2025年1月20日上任首日签署行政命令，撤销拜登政府允许跨性别者...
  title: 特朗普重返白宫计划禁跨性别军人 美军1.5万人恐强制退役
  visited_date: '2025-01-12 17:49:29'
3efb28b155ecc93ea1af33633fa5f5be:
  link: https://m.video.creaders.net/blog/d/503232
  snippet: https://www.tiktok.com/t/ZP8NUAXgP. ～～～～～～～～～～～～～～～～～～～～. 川普总统：. 2020窃选是一次政治劫持，也是我国历史上的低谷，竟然会发生这样的事情。
  title: 聪明女人远多于川黑反川蠢女人. 亲跨性别邪教袭击南希·梅斯
  visited_date: '2025-01-12 17:41:59'
4a1b9e522dcbd6acedd83541e09161ef:
  link: https://m.thepaper.cn/newsDetail_forward_29476839
  snippet: 11月20日，国际跨性别纪念日（Transgender Day of Remembrance）再次提醒我们关注跨性别者所面临的挑战和不公。随着社会对性别认同和表达的讨论愈发开放，跨性别群体的生活...
  title: 当男孩穿上裙子，你怎么看？
  visited_date: '2025-01-12 17:41:39'
4dd4d2c67af15c12af43245a13dcba9b:
  link: https://info.51.ca/articles/1374851
  snippet: 武汉市一名男大生向学校提交了“性别变更申请”，没想到校方直接公布其姓名、班级、身分证字号等个人资讯。此事在网上引起两派讨论，有人认为“男孩变女孩，住哪个寝室、上...
  title: 疯传：华中科技大学张贴出了一张“变性”公示_无忧资讯
  visited_date: '2025-01-12 17:39:21'
525097ecd7a92ea38da55a0cf4894d90:
  link: https://guangming.com.my/%E7%89%B9%E6%9C%97%E6%99%AE%E7%BE%8E%E5%AE%98%E6%96%B9%E6%94%BF%E7%AD%96%E4%BB%85%E4%B8%A4%E7%A7%8D%E6%80%A7%E5%88%AB-%E4%B8%8D%E8%AE%A9%E7%94%B7%E6%80%A7%E5%8F%82%E5%8A%A0%E5%A5%B3%E5%AD%90
  snippet: （华盛顿22日综合外电报道）美国总统当选人特朗普今天矢言于上任首日“停止跨性别精神错乱”。他并承诺“不让男性参加女子体育”，并强调美国政府的官方政策“将只有两种性别：...
  title: 特朗普：美官方政策仅两种性别“不让男性参加女子体育” | 精选| 即时 | 国际 | 2024-12-23
  visited_date: '2025-01-12 17:34:05'
536f9c30d3361307daa215773fe3d3d7:
  link: https://m.finance.creaders.net/news/page/1299811
  snippet: 美国总统当选人川普今天矢言于上任首日“停止跨性别精神错乱”。他并承诺“不让男性参加女子体育”，并强调美国政府的官方政策“将只有两种性别：男性和女性”。
  title: LGBT人士噩耗！川普：美官方政策将只有两种性别
  visited_date: '2025-01-12 17:41:03'
54b83b9606d02b94d29ce7638b529f95:
  link: https://dushi.singtao.ca/toronto/%E6%96%B0%E9%97%BB/%E5%8D%B3%E6%97%B6%E5%9B%BD%E9%99%85/%E7%89%B9%E6%9C%97%E6%99%AE%EF%BC%9A%E7%BE%8E%E5%AE%98%E6%96%B9%E6%94%BF%E7%AD%96%E4%BB%852%E7%A7%8D%E6%80%A7%E5%88%AB-%E4%B8%8D%E8%AE%A9%E7%94%B7%E6%80%A7%E5%8F%82%E5%8A%A0%E5%A5%B3/
  snippet: 美国总统当选人特朗普周日前往亚利桑那州凤凰城参加保守派年度盛会“AmericaFest大会”，期间提到跨性别议题，强调要结束“跨性别的疯狂举动”，要将跨性别者逐出军队和小学、...
  title: 特朗普：美官方政策仅2种性别 不让“男性”参加女子赛事
  visited_date: '2025-01-12 17:33:20'
55d974e1d7fed9181df42c86b102115e:
  link: https://news.qq.com/rain/a/20241221A07XDC00
  snippet: 《龙腾世纪4》跨性别总监Corinne Busche最近接受Inverse采访时，将该游戏令人失望的表现归咎于社区玩家的仇恨活动和差评轰炸，暗示这些外部压力盖过了游戏的内部缺陷。
  title: 《龙腾4》跨性别总监为失败开脱：玩家还是不够包容
  visited_date: '2025-01-12 17:48:42'
57339a8450fbb163fd528c18a458f9a1:
  link: https://hk.on.cc/hk/bkn/cnt/entertainment/20241208/bkn-20241208162701151-1208_00862_001_cn.html?view=d
  snippet: 《欧洲电影奖》周六（7日）于瑞士举行，由法国导演Jacques Audiard执导、美国女星素儿莎丹娜（Zoe Saldana）、西班牙跨性别女星Karla
    Sofia Gascon、美国天后Selena Gomez...
  title: 欧洲电影奖︱《毒王女人梦》扫5奖大赢家Selena Gomez被批｜即时新闻｜缤FUN星网｜on.cc东网
  visited_date: '2025-01-12 17:34:48'
5a11a5644d7eb9a4953c05b7bb8ffc09:
  link: https://www.163.com/dy/article/JHT9J1190514BT3D.html
  snippet: 据《泰晤士报》报道，美国当选总统唐纳德·川普计划在其新任期的第一天，即2025年1月20日，通过行政命令禁止变性人入伍。这一政策可能影响多达1.5万名现役变性军人，...
  title: 川普上任第一天，这些人全部“病退”！誓言带美国回归“正常”
  visited_date: '2025-01-12 17:55:40'
5bb83d7c7f1ed2fbc58a327e5fd958e2:
  link: https://cn.nytimes.com/china/20241211/transgender-conversion-china/
  snippet: 公开跨性别者身份后，灵儿被父母送到医院关了三个月，被迫接受了包括多轮电击疗法在内的治疗。她对医院的起诉被受理被中国LGBTQ群体视为一场来之不易的胜利。
  title: 中国首宗跨性别“扭转治疗”诉讼：原告获医院赔偿
  visited_date: '2025-01-12 17:32:26'
6d159fed6fc6d3cc080bc3b993339233:
  link: https://atvnewsonline.com/world/%E7%BE%8E%E5%8F%82%E9%99%A2%E6%8E%A8%E8%BF%9B%E5%9B%BD%E9%98%B2%E6%B3%95%E6%A1%88-%E7%A6%81%E4%BE%9B%E5%86%9B%E4%BA%BA%E5%AD%90%E5%A5%B3%E6%80%A7%E5%88%AB%E8%82%AF%E5%AE%9A%E7%85%A7%E6%8A%A4/
  snippet: 美国联邦参议院（United States Senate）星期一（12月16日）以压倒性多数推进一项总额达8950亿美元（约4兆令吉）的国防政策法案，其中包括禁止为军人跨性别子女提供“性别肯定...
  title: 美参院推进国防法案 禁供军人子女性别肯定照护
  visited_date: '2025-01-12 17:32:00'
72aec2f46f13587e5a451f76f3d04603:
  link: https://atvnewsonline.com/tag/%E8%B7%A8%E6%80%A7%E5%88%AB%E8%AE%AE%E9%A2%98/
  snippet: 首页/跨性别议题. 跨性别议题. 国际 · 特朗普：美国仅认两性禁跨性别者参女子体育. 2024年12月23日12:30. 特朗普承诺上任首日推行新政策，包括禁止跨性别者参与女子体育，...
  title: 跨性别议题
  visited_date: '2025-01-12 17:29:12'
7b802343c2ef5cb30eb1387cced6ee0b:
  link: https://std.stheadline.com/sc/realtime/article/2043047/%E5%8D%B3%E6%99%82-%E5%9C%8B%E9%9A%9B-%E7%89%B9%E6%9C%97%E6%99%AE-%E7%BE%8E%E5%AE%98%E6%96%B9%E6%94%BF%E7%AD%96%E5%83%852%E7%A8%AE%E6%80%A7%E5%88%A5-%E4%B8%8D%E8%AE%93-%E7%94%B7%E6%80%A7-%E5%8F%83%E5%8A%A0%E5%A5%B3%E5%AD%90%E8%B3%BD%E4%BA%8B
  snippet: 美国总统当选人特朗普周日前往亚利桑那州凤凰城参加保守派年度盛会「AmericaFest大会」，期间提到跨性别议题，强调要结束「跨性别的.
  title: 特朗普：美官方政策仅2种性别不让「男性」参加女子赛事| 星岛日报
  visited_date: '2025-01-12 17:51:30'
7c92317e7e7ca0a7ada02aaa01618735:
  link: https://news.mydrivers.com/1/1020/1020683.htm
  snippet: 日前，媒体inverse采访了《龙腾世纪4》总监Corinne Busche，并发布了一篇标题为“Corinne Busche是RPG游戏的统治者，黑子们的征服者”的文章。媒体称赞《龙腾世纪》总监将她...
  title: 《龙腾世纪4》总监谈自己跨性别身份 游戏也应拥抱多样性
  visited_date: '2025-01-12 17:45:49'
850fe1f3d2e5957622fbdc7e5a96ddb2:
  link: https://www.163.com/dy/article/JK4BS13E0553TDUQ.html
  snippet: 我从小就不被别人待见，他们都骂我是变态”，这是35岁王梓淇在接受采访时说的第一句话而“变态”这个词，一直跟随了他26年，因为从九岁开始，王梓淇就发现了自己身体的不正常，...
  title: 35岁雌雄同体的女性，有男女两套器官，她该如何生存下去？
  visited_date: '2025-01-12 17:57:27'
90922e3277b5b012455b9905b018db8a:
  link: https://www.bannedbook.org/bnews/cnnews/20241129/2122366.html
  snippet: 俄亥俄州的共和党籍州长德万（MikeDeWine）签署法案，要求公立与私立学校的学生，只能按照出生性别使用厕所、浴室和宿舍，共和党与保守派人士表示此举符合常识，能够保护儿童...
  title: 俄亥俄州长签署法案 限跨性学生使用厕所
  visited_date: '2025-01-12 17:59:11'
9ce3f429dc54e95b06cd01ce95958009:
  link: https://www.bbc.com/zhongwen/articles/c745e3vqj05o/simp
  snippet: 跨性别女性灵儿（化名）拿到了河北省昌黎县人民法院出具的民事调解书，这使得她成为中国第一位透过法律程序状告性别“扭转”治疗、反对医院强制扭转性别认同并获得赔偿的跨...
  title: 电击扭转治疗、强制收容、过度用药：中国跨性别女性将医院告上法院
  visited_date: '2025-01-12 18:00:34'
a40d87e7a645cb96315b7caca053afdb:
  link: https://info.51.ca/articles/1374472
  snippet: 近日，一份盖有华中科技大学同济医学院护理学院公章的公示在网上流传。该公示称，护理学院一名男学生向学院提交了个人基本身份信息变更申请，因进行性别重置手术缘由，...
  title: 男生做变性手术，高校公示姓名、班级等个人信息_无忧资讯
  visited_date: '2025-01-12 17:38:42'
a90a0704556c5d2df19af79d32405549:
  link: https://news.mydrivers.com/1/1016/1016490.htm
  snippet: 快科技11月28日消息，因为大儿子跨性别一事，让马斯克非常反感同性恋群体。现在，马斯克公开在社交媒体上表示，游戏业已经变得过于“觉醒”，“那些开发商就不能只是好好做...
  title: 马斯克怒怼游戏中政治正确说教：对种族主义、跨性别和阴谋论说不
  visited_date: '2025-01-12 17:44:23'
ae047953bac44404a3f4c18b719c1a51:
  link: https://news.ifeng.com/c/8fEK5tEBMuh
  snippet: 高校本身就是一个理想的“试验场”，包括对待少数群体的态度，如何处理好必要的信息公示与保护变性者个人隐私的关系，都对社会有探索、示范价值。 羽木丨媒体评论员.
  title: 大学妥善公示性别变更信息，也是一种教育
  visited_date: '2025-01-12 17:43:55'
af51b5a2841ca9a6cc0fff17cafe0e2f:
  link: https://atvnewsonline.com/world/%E7%89%B9%E6%9C%97%E6%99%AE%E5%B0%86%E4%B8%AD%E6%AD%A2%E8%B7%A8%E6%80%A7%E5%88%AB%E4%BA%BA%E5%A3%AB%E6%9C%8D%E5%BD%B9-%E6%96%99%E6%89%93%E5%87%BB%E5%86%9B%E9%98%9F%E8%BF%90%E4%BD%9C/
  snippet: 美国当选总统特朗普（Donald Trump）预计在2025年1月20日上任首日签署行政命令，撤销拜登政府允许跨性别者服役的政策，禁止跨性别者在军中服役，然后让数千名现役跨性别...
  title: 特朗普将中止跨性别人士服役 料打击军队运作
  visited_date: '2025-01-12 17:30:04'
b6039668dbb351f455ebcc7e739c0b26:
  link: https://www.bannedbook.org/bnews/cnnews/20241125/2120516.html
  snippet: 川普计划上任第一天，将所有跨性别军人除名。 英国《星期日泰晤士报》11月25日报道，据国防消息人士称，川普计划发布一项行政命令，开除所有美国军队中的跨性别军人。
  title: 上任第一天，川普第一刀要砍向所有跨性别军人
  visited_date: '2025-01-12 17:58:47'
bf3f8a3302795e94d657a66cca4f97f9:
  link: https://pocketimes.sinchew.com.my/news/20241223/pocketimes/6169995
  snippet: 在首次担任总统时，特朗普曾试图禁止TikTok在美国运营，然而在刚过去的总统大选竞选期，他尝到该平台带来的“甜头”后，转而支持TikTok……...
  title: 特朗普未上任已喊执行令 对跨性别者下手 转态允TikTok？
  visited_date: '2025-01-12 17:50:49'
cec2ac6b6a0a8c937a3909d9ad750b98:
  link: https://info.51.ca/articles/1378625
  snippet: 美国总统当选人川普今天矢言于上任首日“停止跨性别精神错乱”。他并承诺“不让男性参加女子体育”，并强调美国政府的官方政策“将只有两种性别：男性和女性”。
  title: 川普：停止精神错乱 美官方政策将只有两种性别_无忧资讯
  visited_date: '2025-01-12 17:40:07'
d84cec084c3f5d5ae09709adbadd77d3:
  link: https://www.backchina.com/news/2024/11/27/945695.html
  snippet: oxsCbyXkn-M 川普提名的新任美国国防部长赫格塞斯出席节目时表示，美军内的变性人士兵与「觉醒主义」，是美军徵兵人数逐渐下降的主要原因。
  title: 川普开始整肃美军了？ 1.5万跨性别士兵将遭驱逐- 美国要闻BackChina Network
  visited_date: '2025-01-12 17:58:26'
deebd712f2b95cb63cb11cf75aae57e4:
  link: https://info.51.ca/articles/1370104
  snippet: 据美国国防部的匿名人士透露，即将上任的未来总统特朗普正计划签署一项行政命令：驱逐美军中所有变性士兵，即禁止一切美军变性，禁止一切已经跨性别的，或计划跨性别的人...
  title: 新政治正确？特朗普上任当天即开除1.5万跨性别军人_无忧资讯
  visited_date: '2025-01-12 17:37:09'
df25836eac151facf799874ecde993d3:
  link: https://news.mydrivers.com/1/1016/1016944.htm
  snippet: 12月1日消息，迪士尼今年年初发布了《小美人鱼》音乐舞台剧的选角公告，其中特别提到女主爱丽儿和男主亚力克要由跨性别者饰演。有外媒记者发现，迪士尼最近偷偷修改了表述...
  title: 迪士尼为《小美人鱼》舞台剧选主角：必须是跨性别者
  visited_date: '2025-01-12 17:44:54'
e069e4e6ba033adacd5916dd171df04e:
  link: https://news.mydrivers.com/1/1020/1020919.htm
  snippet: 《龙腾世纪4》跨性别总监Corinne Busche最近接受Inverse采访时，将该游戏令人失望的表现归咎于社区玩家的仇恨活动和差评轰炸，暗示这些外部压力盖过了游戏的内部缺陷。
  title: 《龙腾世纪4》跨性别总监为失败开脱：玩家还是不够包容
  visited_date: '2025-01-12 17:46:39'
e65608b4e455126dcf4cedd7982a2dc2:
  link: https://user.guancha.cn/main/content?id=1349718&s=fwzwyzzwzbt
  snippet: 突发！美国变性人校园大屠杀及深层原因分析作者：大侠 当地时间12月16日，美国威斯康星州首府麦迪逊市的基督教学校发生枪击事件，目前已造成包括嫌疑人在内的5人死亡...
  title: 逆性而为的咒诅！突发！美国变性人校园大屠杀及深层原因分析
  visited_date: '2025-01-12 17:53:32'
ef167ef04125dd30e73f3613047753c0:
  link: https://m.cnbeta.com.tw/view/1459724.htm
  snippet: 今年年初迪士尼发布了《小美人鱼》音乐舞台剧选角公告，其中提到女主爱丽儿和男主亚力克必须由跨性别者饰演。近日有网友发现，迪士尼偷偷修改了表述方式。
  title: 迪士尼为《小美人鱼》舞台剧选主角 必须跨性别者饰演
  visited_date: '2025-01-12 17:40:41'
f16614220706dae308aca02285525303:
  link: https://www.bannedbook.org/bnews/cnnews/20241218/2129894.html
  snippet: 威斯康辛州一所私立基督教学校当地时间16日上午11时左右惊传枪击事件，造成1名学生、1名教师身亡，另外有6人受伤，警方最新证实枪手是年仅15岁校内女学生洛普诺（Natalie...
  title: 网疯传威州基督教私校枪手是跨性别 警：不清楚也不重要
  visited_date: '2025-01-12 17:59:33'
f60ece222c715fdd86d8fd5d4f8b9b49:
  link: https://voi.id/zh/news/443134
  snippet: 印度尼西亚共和国驻东京大使馆(KBRI)呼吁在2024年圣诞节庆祝活动中建立和谐,使差异成为侨民之间的力量。
  title: 印度尼西亚驻东京大使馆在2024年圣诞节庆祝活动中呼吁跨性别和谐
  visited_date: '2025-01-12 17:54:44'
f70992ab86f8af4be884016c44f78e95:
  link: https://military.china.com/news/13004177/20241223/47781693.html
  snippet: 近日，美国前总统特朗普再次引发热议。他在一次公开讲话中表示，若重新上任，将采取一系列措施限制跨性别者的权利，包括禁止跨性别者参与女子运动、从军以及进入学校。
  title: 特朗普称上任后将让跨性别者离开军队 将禁止跨性别者参军和参与女子运动
  visited_date: '2025-01-12 17:43:29'
f7acd7819d76c85b65b7af060dc31ce3:
  link: https://news.qq.com/rain/a/20241222A07BAM00
  snippet: 近日Reddit上有网友爆料称，CDPR的IP和世界观设计师Cian Maher是一名跨性别意识形态的坚定支持者，他以前任职游戏记者时曾在推特上明确表示自己不喜欢游戏玩家们，...
  title: 曝设计师是跨性别人士后CDPR被翻旧账：老DEI惯犯了
  visited_date: '2025-01-12 17:49:13'
f8ed0c9c0e2abd3a389e329c7a64ab54:
  link: https://news.seehua.com/post/1252589
  snippet: 男生也得保护好自己的安全！德国柏林一名27岁的跨性别女警茱蒂，最近选择前往一间以性爱派对与变装癖闻名的俱乐部玩耍，途中遇到2名长相俊秀、身材英挺的男警，在一见钟情...
  title: 跨性别女警捡尸下药 2男警惨遭侵犯
  visited_date: '2025-01-12 17:50:00'
f95ec5aeccf85941121bd34257bf2012:
  link: https://news.qq.com/rain/a/20241126A038EO00
  snippet: 2025年，美国社会可能将迎来一场前所未有的文化风暴。 11月25日，根据《泰晤士报》报道称，特朗普计划发布一项行政命令，要求将15000名现役的跨性别军人从美军中驱逐出去。
  title: 特朗普重启跨性别禁令：15000名军人面临被驱逐的命运
  visited_date: '2025-01-12 17:47:15'
faef274ed9499b731491d62587ade2e5:
  link: https://stnn.cc/c/2024-12-23/3944795.shtml
  snippet: 候任总统特朗普出席保守派公开活动，重申上任首天就会关闭边境，大规模驱逐无证移民，也会阻止“觉醒”文化，结束跨性别的“疯狂行为”。
  title: 特朗普宣称美国进入新黄金时代，保守派年会讲话抨跨性别者
  visited_date: '2025-01-12 17:51:56'
fc4960d888c01262ffcb07b18a2ea218:
  link: https://entrevue.fr/zh-CN/trump-prevoit-une-serie-de-decrets-pour-stopper-le-delire-transgenre-et-fermer-la-frontiere/
  snippet: 唐纳德·特朗普(Donald Trump) 在20 月战胜卡马拉·哈里斯(Kamala Harris) 后当选美国总统，他承诺在XNUMX 月XNUMX
    日就职时将采取严厉措施。在凤凰城的一次演讲中，这位前...
  title: 特朗普计划发布一系列行政命令以阻止“跨性别疯狂”并关闭边境 - 采访
  visited_date: '2025-01-12 17:33:44'
fd7c3392fc7d2f9099ce788dfb869dbb:
  link: https://atvnewsonline.com/world/%E7%89%B9%E6%9C%97%E6%99%AE%EF%BC%9A%E7%BE%8E%E5%9B%BD%E4%BB%85%E8%AE%A4%E4%B8%A4%E6%80%A7-%E7%A6%81%E8%B7%A8%E6%80%A7%E5%88%AB%E8%80%85%E5%8F%82%E5%A5%B3%E5%AD%90%E4%BD%93%E8%82%B2/
  snippet: 美国总统当选人特朗普12月22日（星期日）表示，他将在上任首日“停止跨性别精神错乱”，并承诺“不允许男性参与女子体育”，强调美国政府的官方政策将仅承认“男性和女性”两种...
  title: 特朗普：美国仅认两性 禁跨性别者参女子体育
  visited_date: '2025-01-12 17:31:08'
ffd26ca24c4f48c7150d2d83459d43ff:
  link: https://user.guancha.cn/main/content?id=1340658
  snippet: 天下事2024年11月28日22:30:38 来自北京市美联社当地时间11月28日报道，美共和党州长迈克·德怀恩周三表示，他已签署一项措施，禁止俄亥俄州公立和...
  title: 美俄亥俄州州长签署法案限制跨性别学生使用卫生间
  visited_date: '2025-01-12 17:53:02'
