- title: 未成年可做變性手術惹議 家長團體憂心國外後悔案例多
  link: https://www.epochtimes.com/gb/25/1/14/n14413337.htm
  snippet: 卫福部去年底公告“LGBT+民众医疗照护参考指引”，开放未成年的12到18岁儿少，有条件准许、执行变性手术，家长团体14日表示，青春期的青少年身心灵发育都还在迈向成熟的阶段，...
- title: 台湾跨性别老师黄明真：从被逼离职到获“教育界奥斯卡奖”师铎奖，社会真的更包容多元了吗？
  link: https://www.bbc.com/zhongwen/articles/crmnp990px7o/simp
  snippet: 台湾教师黄明真获颁教育部最高荣誉奖，她相隔近20年两度上新闻，台湾社会风气有所改变。但她仍认为“我不是第一”。
- title: 泰国男子变性手术失败 需通过腹部穿孔排便
  link: https://www.8world.com/southeast-asia/thai-mans-sex-reassignment-surgery-fails-2674711
  snippet: 泰国一名男子进行变性手术，创建人造外阴和阴道，但人造阴道在术后数个月破裂，医生将她的大肠重新定位靠近胃部，并在腹部开一个孔作为粪便排放道。时隔八个月伤口依然没有...
- title: 未成年变性手术卫福部称仅限双性人- 生活新闻- 中国时报
  link: https://www.chinatimes.com/cn/newspapers/20250114000453-260114?ctrack=mo_main_recmd_p15
  snippet: 卫福部去年底订定「LGBT+民眾医疗照护参考指引」，其中「未成年双性人之医疗手术共同性建议原则」提出，对于12到18岁有适应困难者，经专业团队评估后可进行手术，...
- title: 美国通过立法：禁止跨性别女学生参加中小学校的女生体育项目
  link: https://news.mydrivers.com/1/1025/1025568.htm
  snippet: 1月16日消息，据国外媒体报道称，美国众议院今天通过立法，禁止跨性别女学生参加中小学校的女生体育项目。这项法案以218票对206票，几乎完全按照党派划线获得通过，...
- title: 泰国最美“人妖皇后”嫁入中国9年后依旧恩爱引网友羡慕- 人物
  link: https://www.cnbeta.com.tw/articles/movie/1467622.htm
  snippet: 1月1日消息，泰国的人妖文化全球知名，已经有不少选美的“人妖皇后”诞生，今天想和大家分享一位与中国有特殊情缘的“人妖皇后”妮莎（NisaSelaw）。2015年，妮莎与中国一位富商...
- title: 川普宣誓就職後 計劃發布逾百行政命令
  link: https://www.ntdtv.com/gb/2025/01/20/a103949994.html
  snippet: 美国总统川普1月20日就职后，可能发布超过100条行政令，兑现竞选承诺。
- title: 衛福部准未成年變性 家長團體：危險徵兆
  link: https://www.epochtimes.com/gb/25/1/14/n14413376.htm
  snippet: 【大纪元2025年01月14日讯】（大纪元记者赖玟茹、戴德蔓、庄瑷筠台湾台北报导）卫福部去年底公告“LGBT+（性多样）民众医疗照护参考指引”，有条件准许、执行变性手术，引发...
- title: “我想去泰国！”，《鱿鱼游戏2》 跨性别者角色引发关注
  link: https://www.thaiheadlines.com/162774/
  snippet: 泰国头条新闻社讯据泰国媒体报道，12月26日，大热韩剧《鱿鱼游戏2》开播，其中跨性别者角色“Jo Hyun Joo”（朴成焄饰）引发网友和观众广泛关注。剧中，120号玩家Jo
    Hyun Joo...
- title: 切肋骨瘦腰还想制成皇冠美国变性网红疯狂举动惹议| 国际 | 2025-01-21
  link: https://guangming.com.my/%E5%88%87%E8%82%8B%E9%AA%A8%E7%98%A6%E8%85%B0%E8%BF%98%E6%83%B3%E5%88%B6%E6%88%90%E7%9A%87%E5%86%A0-%E7%BE%8E%E5%9B%BD%E5%8F%98%E6%80%A7%E7%BD%91%E7%BA%A2%E7%96%AF%E7%8B%82%E4%B8%BE%E5%8A%A8%E6%83%B9
  snippet: （华盛顿21日讯）美国堪萨斯城的一个变性女网红，进行了切除部分肋骨的手术，只为让腰围变细；手术后她更要求收藏被取出的肋骨，可能打算用来制作一顶皇冠，让人听了浑身不...
- title: 活跃在中国和世界舞台的朝鲜族变性舞蹈演员金星(57岁)的演出在中国国内接连被取消，其背景备受关注。
  link: https://www.mk.co.kr/cn/world/11209966
  snippet: 3日(当地时间)，据CNN等媒体报道，最近中国当局无缘无故突然取消著名变性人金兴的演出的事例正在增加。 去年年末,广州以"文件不足"为由取消了晋兴的剧场演出,其他地区的...
- title: 中国第一变性人,隐瞒男儿身嫁大32岁富商,如今..._无忧资讯
  link: https://info.51.ca/articles/1382905
  snippet: 在社会多元化发展的今天，变性群体逐渐走进大众视野，可在几十年前，这一话题还极为敏感隐晦。而“张克莎” 这个名字，如同一颗投入平静湖面的巨石，在中国性别认知领域激起千...
- title: IG突上传色情版《鱿鱼游戏》 朴成焄承认是罪魁祸“手”
  link: https://www.zaobao.com.sg/entertainment/story20241230-5664688
  snippet: （首尔讯）全球夯剧《鱿鱼游戏2》12月26日上线，虽然外媒批评“不如第一季”，但该剧热潮不减。朴成焄（Park Sunghoon）在剧中饰演一名跨性别者，12月30日，他的Instagram（IG）...
- title: 衛福部LGBT指引 台聯黨：偷渡混淆生理性別
  link: https://www.epochtimes.com/gb/25/1/14/n14413375.htm
  snippet: 针对近期卫福部公告“LGBT+民众医疗照护参考指引”，内文要求医事人员要具备分辨性倾向、性认同、性行为之间的差别。台联党认为，医学是本着生物学学理的学问，因生理构造、...
- title: 马斯克再次站台支持反觉醒:DEI是肿瘤！要及时切除
  link: https://www.yeeyi.com/news/details/2589481/
  snippet: 特斯拉首席执行官埃隆·马斯克对于DEI的痛恨可谓深入骨髓，近日他再度发言，为反DEI站台。 美国主持人Charlie Kirk发文表示：“DEI不仅仅是一种'
- title: 中美俄新共识:抗击觉醒文化/邱立本
  link: https://www.enanyang.my/node/644201
  snippet: 中美俄最新共识就是反对觉醒文化，反对男女不分和跨性别，反对毒品与零元购；进入大谈判和大交换时代，要和平繁荣，远离战争，寻找打开和平大门的秘密钥匙。
- title: 切肋骨瘦腰还想制成皇冠 美国变性网红疯狂举动惹议 - 国际 - 带你看世界
  link: https://www.sinchew.com.my/news/20250121/international/6234822
  snippet: （华盛顿21日讯）美国堪萨斯城的一个变性女网红，进行了切除部分肋骨的手术，只为让腰围变细；手术后她更要求收藏被取出的肋骨，可能打算用来制作一顶皇冠，让人听了浑身不...
- title: 知道行动带来的结果的选择和不知道的选择会产生不同层次的伦理意义。 拥有选择权利和结果知识的人类在极端情况下做出的决定,超越个人,体现出物种的可能性。时隔3年回归的《鱿鱼游戏》第二季描述了456名游戏参..
  link: https://www.mk.co.kr/cn/culture/11204039
  snippet: 知道行动带来的结果的选择和不知道的选择会产生不同层次的伦理意义。 拥有选择权利和结果知识的人类在极端情况下做出的决定,超越个人,体现出物种的可能性。
- title: 27岁网红1尸2命 “吃晚餐噎到” 家人面前窒息亡 - 国际 - 即时国际
  link: https://www.sinchew.com.my/news/20250107/international/6200280
  snippet: （华盛顿7日讯）美国27岁多明尼加裔网红卡萝（Carol Acosta）育有2名年幼子女，去年7月才宣布怀了第三胎，IG拥有逾670万粉丝，日前在纽约与家人外出用餐时，疑似因噎到造成心脏...
- title: 税收局推广税务醒觉 委网红名人任策略伙伴 - 国内 - 全国综合
  link: https://www.sinchew.com.my/news/20241228/nation/6178440
  snippet: （布城28日讯）内陆税收局（LHDN）委任26名社交媒体网红和名人为策略合作伙伴，以制作能提升税务醒觉、教育和履行纳税责任的内容。税收局文告指出，这些税收局策略...
- title: 马斯克再次站台支持反觉醒:DEI是肿瘤！要及时切除
  link: http://news.17173.com/content/01172025/101205613.shtml
  snippet: 特斯拉首席执行官埃隆·马斯克对于DEI的痛恨可谓深入骨髓，近日他再度发言，为反DEI站台。 美国主持人Charlie Kirk发文表示：“DEI不仅仅是一种'干扰'，它更是一个肿瘤，除非...
- title: 误传色情版《鱿鱼游戏》照 朴成焄自嘲罪魁祸“手”
  link: https://atvnewsonline.com/world/%E6%9C%B4%E6%88%90%E7%84%84%E7%BD%91%E4%BC%A0%E8%89%B2%E6%83%85%E7%89%88%E3%80%8A%E9%B1%BF%E9%B1%BC%E6%B8%B8%E6%88%8F%E3%80%8B%E7%85%A7-%E6%89%BF%E8%AE%A4%E6%98%AF%E7%BD%AA%E9%AD%81%E7%A5%B8/
  snippet: 全球热议剧集《鱿鱼游戏2》于2024年12月26日回归，尽管外界评价褒贬不一，但该剧的人气依然高涨。剧中扮演跨性别角色的朴成焄（Park Sunghoon）因其在剧中为筹集变性手术...
- title: 跨性别：中国高校公示学生出柜信息引争议
  link: https://www.bbc.com/zhongwen/articles/czxkv0qzqwzo/simp
  snippet: 华中科技大学将一位跨性别女性在校生变更身份证性别的详情资料张贴公示，文件详细记录学生姓名以及资讯更新缘由。此举引发民众关于个人隐私过度揭露的惶恐。
- title: 特朗普会阻止“跨性别疯狂”吗？
  link: https://chinese.aljazeera.net/news/political/2024/12/25/%E7%89%B9%E6%9C%97%E6%99%AE%E4%BC%9A%E9%98%BB%E6%AD%A2%E8%B7%A8%E6%80%A7%E5%88%AB%E7%96%AF%E7%8B%82%E5%90%97
  snippet: 复杂性和阻碍性. 与禁止男女性别歧视相反，跨性别身份并未得到宪法承认，这将使跨性别者在基于性别的歧视方面的法律地位变得复杂化和受到阻碍。 共和党保守派获得6
    票多数，而...
- title: 肉身，割裂，重建的自我：台湾四位跨性别者的手术记事
  link: https://theinitium.com/zh-hans/article/20250109-taiwan-four-transgender-journeys
  snippet: 我最大的心愿，就是有一天可以搬出去，找一个自己的空间，放自己喜欢的衣服，自由地化妆，到时候我就不用再演了。 跨性别者琳子。摄：陈焯煇/端传媒.
- title: 英国跨性别模特“隐瞒实情”和男孩亲密，遭当街报复，19岁孤女是领头者
  link: https://news.qq.com/rain/a/20250117A00YJH00
  snippet: 当地时间1月16日，伦敦警察厅公布了一段由街头监控拍下的视频，可以看到戴着面具和手套的蒙面歹徒埋伏在停车场等待，当面带微笑的毫无戒心的受害者靠近时，他们对她拳打脚...
- title: 特朗普称上任第一天就要阻止 “变性妄想”
  link: https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20241222-%E7%89%B9%E6%9C%97%E6%99%AE%E7%A7%B0%E4%B8%8A%E4%BB%BB%E7%AC%AC%E4%B8%80%E5%A4%A9%E5%B0%B1%E8%A6%81%E9%98%BB%E6%AD%A2-%E5%8F%98%E6%80%A7%E5%A6%84%E6%83%B3
  snippet: 这位将在1月20日就职的美国总统称：“我将签署行政命令，结束切割儿童生殖器的做法，将跨性别者排除在军队之外，并将他们排除在小学、初中和高中之外”。
- title: 健身房跨性別爭議引華人恐慌 律師籲平衡多方需求
  link: https://www.epochtimes.com/gb/25/1/9/n14409415.htm
  snippet: 日前，居住在亚凯迪亚市（Arcadia）的华人陈女士于洛杉矶一间连锁健身房的女性更衣室内，发现一名声线粗旷、外表疑似男性的使用者。
- title: 美国众议院通过法案 禁跨性别学生参加女子运动
  link: https://www.swissinfo.ch/chi/%E7%BE%8E%E5%9B%BD%E4%BC%97%E8%AE%AE%E9%99%A2%E9%80%9A%E8%BF%87%E6%B3%95%E6%A1%88-%E7%A6%81%E8%B7%A8%E6%80%A7%E5%88%AB%E5%AD%A6%E7%94%9F%E5%8F%82%E5%8A%A0%E5%A5%B3%E5%AD%90%E8%BF%90%E5%8A%A8/88724687
  snippet: 法新社华盛顿14日电） 美国由共和党人把持的联邦众议院今天通过一项法案，严格限制跨性别运动员参加女孩与女子运动。 这项立法将禁止跨性别学生参加任何接受联邦资助的...
- title: 變性者參與女子體育賽事？ 加州議員提案禁止
  link: https://www.ntdtv.com/gb/2025/01/16/a103948580.html
  snippet: 【新唐人北京时间2025年01月16日讯】周二（14日），美国国会众议院通过了“禁止跨性别学生参与女子体育赛事”的法案，同时，加州共和党立法者也提出了一项类似的提案，确保只有...
- title: 2024年终专题：台港跨性别议题的讨论与回响｜端闻 Podcast
  link: https://theinitium.com/zh-hans/audio/20250102-initium-audio-end-of-year-review-transgender-issue
  snippet: 这些恐惧与不信任扩大为偏见，落到个体身上，就会造成具体的伤害。
- title: 曝《龙腾4》跨性别总监离职！工作室恐被关闭
  link: https://www.163.com/dy/article/JM3O1NR40526K1KN.html
  snippet: 据外媒爆料，《龙腾世纪4》的跨性别总监CorinneBusche现已从Bioware和EA离职。此外，爆料还称负责开发《龙腾世纪4》的BioWare埃德蒙顿工作室将于2025年2月关闭。
- title: 《鱿鱼游戏2》「跨性别者」朴成焄演技受肯定！观众：让我感觉他就是女人
  link: https://www.koreastardaily.com/sc/news/156419
  snippet: Netflix原创韩剧《鱿鱼游戏》凭藉第一季在全球掀起收视热潮，片中的游戏场景、红绿灯娃娃、面具设计等元素成为流行符号，甚至被改编为主题公园、游戏和商品。
- title: 曝设计师是跨性别人士后CDPR被翻旧账：老DEI惯犯了
  link: https://news.qq.com/rain/a/20241222A07BAM00
  snippet: 近日Reddit上有网友爆料称，CDPR的IP和世界观设计师Cian Maher是一名跨性别意识形态的坚定支持者，他以前任职游戏记者时曾在推特上明确表示自己不喜欢游戏玩家们，...
- title: 特朗普：在我领导下，美国只有两种性别
  link: https://news.ifeng.com/c/8fYaVDjXEmQ
  snippet: 美国当选总统特朗普当地时间23日在美亚利桑那州凤凰城发表了超过70分钟的长篇演讲，特朗普本人称这一演讲是他的政府将带来的“常识革命的小小预演”。在演讲中，他承诺将在...
- title: 德州總檢察長控告NCAA涉嫌誤導性別政策
  link: https://www.epochtimes.com/gb/24/12/26/n14398569.htm
  snippet: 德克萨斯州总检察长Ken Paxton 于12月22日对美国大学体育协会（NCAA）提起诉讼，指控其误导观众，让他们以为自己正在观看同一性别运动员之间的比赛。
- title: 《龙腾世纪4》跨性别总监为失败开脱：玩家还是不够包容
  link: https://news.mydrivers.com/1/1020/1020919.htm
  snippet: 《龙腾世纪4》跨性别总监Corinne Busche最近接受Inverse采访时，将该游戏令人失望的表现归咎于社区玩家的仇恨活动和差评轰炸，暗示这些外部压力盖过了游戏的内部缺陷。
- title: 有点像打雷姐（跨性别版）
  link: https://i.ifeng.com/c/8g5XQOZgslj
  snippet: 全球首位跨性别戛纳影后Karla Sofía Gascón 最近在美国颁奖季度横扫。 “特别声明：以上作品内容(包括在内的视频、图片或音频)为凤凰网旗下自媒体平台“大风号”用户上传并...
- title: 眾院通過法案 跨性別學生「禁參加」女子體育賽事
  link: https://www.worldjournal.com/wj/story/124238/8491751?from=wj_catelistnews&zh-cn
  snippet: 总统当选人川普矢言「停止跨性别精神错乱」，强调美国政府的官方政策「将只有两种性别：男性和女性」，不会让男性参加女子体育。...
- title: 褒姒！有一个算一个！曝《龙腾世纪4》跨性别总监离职！ 工作室恐被关闭
  link: https://www.msn.com/zh-cn/gaming/other/%E8%A4%92%E5%A7%92-%E6%9C%89%E4%B8%80%E4%B8%AA%E7%AE%97%E4%B8%80%E4%B8%AA-%E6%9B%9D-%E9%BE%99%E8%85%BE%E4%B8%96%E7%BA%AA4-%E8%B7%A8%E6%80%A7%E5%88%AB%E6%80%BB%E7%9B%91%E7%A6%BB%E8%81%8C-%E5%B7%A5%E4%BD%9C%E5%AE%A4%E6%81%90%E8%A2%AB%E5%85%B3%E9%97%AD/ar-AA1xlBSv
  snippet: 据国外媒体报道，《龙腾世纪4》的跨性别游戏总监Corinne Busche已正式从Bioware及EA(艺电)公司离职。
- title: 联邦法庭裁定违宪，拜登政府跨性别学生保护举措受挫
  link: https://stnn.cc/c/2025-01-10/3949453.shtml
  snippet: 肯塔基州联邦法庭裁定，拜登政府无权扩大为了保障跨性别学生，而扩大《教育法修正案第九条》（Title IX）的适用范围，教育部的行为超越职权，也侵犯了教师的言论自由。
- title: 姚耀光：厕所的争论
  link: https://www.zaobao.com.sg/lifestyle/columns/story20250111-5697106
  snippet: 去年底，美国民主党众议员萨拉·麦克布莱德（Sarah McBride）成为美国首位当选国会议员的跨性别者，这一历史性事件引发了一场关于厕所使用的争论。
- title: 又抹黑跨性別 川普：美官方政策將只有兩種性別
  link: https://www.worldjournal.com/wj/story/124279/8442721?zh-cn
  snippet: 总统当选人川普今天矢言于上任首日「停止跨性别精神错乱」。他并承诺「不让男性参加女子体育」，并强调美国政府的官方政策「将只...
- title: 曝设计师是跨性别人士后CDPR被翻旧账：老DEI惯犯了
  link: https://www.yeeyi.com/news/details/2567535/
  snippet: 此前我们曾报道过，近日Reddit上有网友爆料称，CDPR的IP和世界观设计师Cian Maher是一名跨性别意识形态的坚定支持者，他以前任职游戏记者时曾在推特.
- title: 特朗普：美官方政策仅2种性别，不让“男性”参加女子赛事
  link: https://stnn.cc/c/2024-12-23/3944707.shtml
  snippet: 美国总统当选人特朗普周日前往亚利桑那州凤凰城参加保守派年度盛会“AmericaFest大会”，期间提到跨性别议题，强调要结束“跨性别的疯狂举动”，要将跨性别者逐出军队和小学、...
- title: 曝《龙腾4》跨性别总监离职！ 工作室恐被关闭
  link: https://www.msn.com/zh-cn/gaming/other/%E6%9B%9D-%E9%BE%99%E8%85%BE4-%E8%B7%A8%E6%80%A7%E5%88%AB%E6%80%BB%E7%9B%91%E7%A6%BB%E8%81%8C-%E5%B7%A5%E4%BD%9C%E5%AE%A4%E6%81%90%E8%A2%AB%E5%85%B3%E9%97%AD/ar-AA1xlp3k
  snippet: 据外媒爆料，《龙腾世纪4》的跨性别总监Corinne Busche现已从Bioware和EA离职。
- title: 健身房更衣室遇跨性別者 華女感不適
  link: https://www.worldjournal.com/wj/story/121359/8473298?zh-cn
  snippet: 南加州天普市（Temple City）一家连锁健身房女性更衣室，华人陈小姐发现一名外表疑似男性的用户。当她向工作人员报...
- title: 英钩协官宣禁跨性别参加女钩赛| 精选| 体育 | 2025-01-09
  link: https://guangming.com.my/%E8%8B%B1%E9%92%A9%E5%8D%8F%E5%AE%98%E5%AE%A3-%E7%A6%81%E8%B7%A8%E6%80%A7%E5%88%AB%E5%8F%82%E5%8A%A0%E5%A5%B3%E9%92%A9%E8%B5%9B
  snippet: （伦敦9日讯）英格兰钩球协会宣布，从下赛季开始，禁止跨性别女性参加女子组别的比赛。 为解决跨性别和非二元性别者的参与问题，英格兰钩球协会设立了两个比赛类别：女子组和...
- title: 拜登撤回 保障跨性别运动员提案
  link: https://www.chinapress.com.my/20241222/%E6%8B%9C%E7%99%BB%E6%92%A4%E5%9B%9E-%E4%BF%9D%E9%9A%9C%E8%B7%A8%E6%80%A7%E5%88%AB%E8%BF%90%E5%8A%A8%E5%91%98%E6%8F%90%E6%A1%88/
  snippet: （华盛顿22日综合电）多家媒体在周日报导，美国总统拜登先前计划从“1972年教育法修正案”第九条（Title IX）延伸，制定一项规则来保障大学跨性别运动员权益，现在决定放弃这项...
- title: 眾院通過法案 禁止跨性別學生參加女子運動賽事
  link: https://www.worldjournal.com/wj/story/121468/8490616?from=wj_maintab_cate&zh-cn
  snippet: 共和党主导的众院14日通过法案，禁止跨性别学生参加由联邦资助的学校所举办的女子运动赛事。 投票结果为218票赞成、206票反对；所有共和党议员皆投下赞成票，只有两名...
- title: 美众院通过法案 禁跨性别学生参加女子运动赛事 - 国际 - 即时国际
  link: https://www.sinchew.com.my/news/20250115/international/6222509
  snippet: （华盛顿15日综合电）美国众议院14日通过一项法案，禁止跨性别学生参加由联邦资助的学校所举办的女子运动赛事。法案在共和党主导的众院以218票赞成、206票反对中通过，...
- title: 《龙腾4》跨性别总监离职 玩家:快失业别祸害别的游
  link: https://www.yeeyi.com/news/details/2591668/
  snippet: 昨日据外媒爆料，《龙腾世纪：影障守护者》的跨性别总监Corinne Busche现已从Bioware和EA离职，业内知名人士Jeff Grubb也证实了这一点。
- title: 璀璨女人夢…坎城首名「跨性別影后」 入圍「英國奧斯卡」
  link: https://www.worldjournal.com/wj/story/121232/8494421?zh-cn
  snippet: 首名坎城影展跨性别影后卡拉加斯康得奖片「璀璨女人梦」，去年11月全美上映。对于近日洛杉矶野火，卡拉加斯康表达「心碎」，并...
- title: 美国政策将只承认两种性别 特朗普:禁生理男参加女子体育
  link: https://www.enanyang.my/node/641892
  snippet: 美国候任总统特朗普22日矢言，他上任首日将“停止跨性别精神错乱”。
- title: Meta大改政策 允说同志跨性别人士“有精神病” “不正常” - 国际 - 即时国际
  link: https://www.sinchew.com.my/news/20250108/international/6203183
  snippet: （华盛顿8日综合电）社交媒体巨头Meta周二宣布大幅调整内容审核政策，包括终止美国的事实核查计划，不再进行专业事实查核。除此之外，Meta还悄悄更新针对仇恨内容的政策，...
- title: 【特朗普重返白宫】特朗普扬言“制止LGBTQ疯狂行为”
  link: https://www.orientaldaily.com.my/news/international/2024/12/23/701286
  snippet: （菲尼克斯23日讯）美国候任总统特朗普当地时间周日誓言，在他上任的第一天就“制止跨性别者的疯狂行为”，而即将控制美国国会两院和白宫的共和党，将继续反对LGBTQ（同性恋、...
- title: 专栏乔靖夫│跨性别选手遭杯葛风暴| 星岛日报
  link: https://std.stheadline.com/sc/realtime/article/2044914/%E5%8D%B3%E6%99%82-%E9%AB%94%E8%82%B2-%E5%B0%88%E6%AC%84-%E5%96%AC%E9%9D%96%E5%A4%AB%E2%94%82%E8%B7%A8%E6%80%A7%E5%88%A5%E9%81%B8%E6%89%8B%E9%81%AD%E6%9D%AF%E8%91%9B%E9%A2%A8%E6%9A%B4
  snippet: 早前的巴黎奥运因为女性拳击选手的性别被质疑而引起颇大风波，其实关于跨性别运动员的争议在西方国家体育界一直在燃烧，近期比较瞩目的是美国西.
- title: 【特朗普重返白宫】特朗普2.0终止多元性别 只承认男性和女性
  link: https://www.orientaldaily.com.my/news/international/2025/01/21/707331
  snippet: （华盛顿21日讯）重返白宫的特朗普当地时间周一发表就职演说，誓言将法律秩序带回社会，他宣布终止多元性别，并表示从今天起，他领导下美国政府的正式政策将只有两种性别：...
- title: 特朗普誓上台后迅速行动 反移民 反跨性别 贸易战 - 国际 - 国际头条
  link: https://www.sinchew.com.my/news/20250119/international/6232777
  snippet: （华盛顿19日综合电）美国候任总统特朗普将在当地时间周一（20日）宣誓就职，成为美国第47任总统。特朗普矢言在周一重返白宫后，将采取大规模和快速的行动，包括大规模驱逐...
- title: 跨性别女切6根肋骨瘦身 还打算制肋骨皇冠
  link: https://www.chinapress.com.my/20250115/%E8%B7%A8%E6%80%A7%E5%88%AB%E5%A5%B3%E5%88%876%E6%A0%B9%E8%82%8B%E9%AA%A8%E7%98%A6%E8%BA%AB-%E8%BF%98%E6%89%93%E7%AE%97%E5%88%B6%E8%82%8B%E9%AA%A8%E7%9A%87%E5%86%A0/
  snippet: （华盛顿15日综合电）美国一名跨性别女子为了追求纤细的腰身，不惜动手术取出六根肋骨。更令人惊讶的是，为了不要“浪费”，她打算用这些取出的肋骨，做成一顶“肋骨皇冠”，...
- title: 特朗普重入白宫｜特朗普终止多元性别 美国只承认男和女
  link: https://www.chinapress.com.my/20250121/%E7%89%B9%E6%9C%97%E6%99%AE%E9%87%8D%E5%85%A5%E7%99%BD%E5%AE%AB%EF%BD%9C%E7%89%B9%E6%9C%97%E6%99%AE%E7%BB%88%E6%AD%A2%E5%A4%9A%E5%85%83%E6%80%A7%E5%88%AB-%E7%BE%8E%E5%9B%BD%E5%8F%AA%E6%89%BF%E8%AE%A4/
  snippet: （华盛顿21日综合电）美国总统特朗普20发表就职演说，誓言将法律秩序带回社会，他宣布终止多元性别，并表示从今天起，美国政府的正式政策将只有两种性别：男性和女性。
- title: 美国众议院通过法案 限制跨性别学生参与体育竞赛
  link: https://www.bannedbook.org/bnews/sports/20250116/2141902.html
  snippet: 美国联邦众议院今天通过共和党籍候任总统川普支持的一项法案，对没有遵守规定的学校扣留联邦资金，实质上禁止跨性别女孩与妇女参与学校体育竞赛。 美国联邦众议院通过...
- title: 特朗普：美国仅认两性 禁跨性别者参女子体育
  link: https://atvnewsonline.com/world/%E7%89%B9%E6%9C%97%E6%99%AE%EF%BC%9A%E7%BE%8E%E5%9B%BD%E4%BB%85%E8%AE%A4%E4%B8%A4%E6%80%A7-%E7%A6%81%E8%B7%A8%E6%80%A7%E5%88%AB%E8%80%85%E5%8F%82%E5%A5%B3%E5%AD%90%E4%BD%93%E8%82%B2/
  snippet: 美国总统当选人特朗普12月22日（星期日）表示，他将在上任首日“停止跨性别精神错乱”，并承诺“不允许男性参与女子体育”，强调美国政府的官方政策将仅承认“男性和女性”两种...
- title: '川普誓言上任首日阻止「跨性别疯狂」: 美国官方政策只有两种性别'
  link: https://www.soundofhope.org/post/859335
  snippet: '美国候任总统#川普周日（22日）表示，他将在上任第1天，阻止「 #跨性别疯狂」（transgender lunacy），而准备控制国会参众两院及白宫的#共和党人也将继续对抗#LGBTQ
    权利。'
- title: 美众议院通过法案 禁跨性别学生参与体育竞赛
  link: https://atvnewsonline.com/world/%E7%BE%8E%E4%BC%97%E8%AE%AE%E9%99%A2%E9%80%9A%E8%BF%87%E6%B3%95%E6%A1%88-%E7%A6%81%E8%B7%A8%E6%80%A7%E5%88%AB%E5%AD%A6%E7%94%9F%E5%8F%82%E4%B8%8E%E4%BD%93%E8%82%B2%E7%AB%9E%E8%B5%9B/
  snippet: 美国联邦众议院星期二（1月14日）通过共和党籍候任总统特朗普支持的一项法案，对没有遵守规定的学校扣留联邦资金，实质上禁止跨性别女孩与妇女参与学校体育竞赛。
- title: 曝《龙腾4》跨性别总监离职！工作室恐被关闭
  link: http://news.17173.com/content/01172025/182103536.shtml
  snippet: 据外媒爆料，《龙腾世纪4》的跨性别总监Corinne Busche现已从Bioware和EA离职。 此外，爆料还称负责开发《龙腾世纪4》的BioWare埃德蒙顿工作室将于2025年2月关闭。
- title: 《龙腾4》跨性别总监离职 玩家:快失业别祸害别的游
  link: https://news.17173.com/content/01182025/170301755.shtml
  snippet: 昨日据外媒爆料，《龙腾世纪：影障守护者》的跨性别总监Corinne Busche现已从Bioware和EA离职，业内知名人士Jeff Grubb也证实了这一点。曝出的告别邮件中，Corinne
    Busche...
- title: 跨性别议题
  link: https://atvnewsonline.com/tag/%E8%B7%A8%E6%80%A7%E5%88%AB%E8%AE%AE%E9%A2%98/
  snippet: 特朗普承诺上任首日推行新政策，包括禁止跨性别者参与女子体育，并仅承认“男性和女性”两种性别。 阅读. 关注. Facebook · YouTube
    · Instagram · Telegram · TikTok.
- title: 1/15/2025 川普国防部长确认听证会；民主党抹黑新投票通过的禁跨性别学生参加女子运动法案
  link: https://www.bannedbook.org/bnews/sohnews/20250116/2142162.html
  snippet: '来源: US News Express美国时事通, 文章内容并不代表本网立场和观点。 1/15/2025 川普国防部长确认听证会；民主党抹黑新.
    感恩您的捐赠、点赞、留言和和关注！'
